### ISSUE TITLE
要望（？）

### ISSUE THREAD

**Issue by rartangem** [takevox/suikachau#8]
各種音声(BGM・合成時のSEなど)の音量を0～100%+ミュートボタンでいじれるようになると嬉しいです

**Comment by rartangem** [comment]
ゲーム本体(.exe)のアイコンを設定したらいかがでしょうか（アイコンがGODOT Engineのものだったので....）
rceditを導入(macOS&LinuxであればWINEも)し、
↓
(プロジェクトを開いて)エディター→エディター設定→rceditを検索→rcedit.exeのパス指定
↓
(プロジェクトを開いて)プロジェクト設定→アプリケーション→構成→任意の.png形式の画像（

（後ほど記載）

**Comment by takevox** [comment]
> 各種音声(BGM・合成時のSEなど)の音量を0～100%+ミュートボタンでいじれるようになると嬉しいです

各種音声の設定がほしい #10 
として分岐しました。

**Comment by takevox** [comment]
> ゲーム本体(.exe)のアイコンを設定したらいかがでしょうか（アイコンがGODOT Engineのものだったので....） https://docs.godotengine.org/en/stable/tutorials/export/changing_application_icon_for_windows.html

アイコン設定しました。
