### ISSUE TITLE
（バグ）挟まるように合成されたときに無限に合成のSEが流れる

### ISSUE THREAD

**Issue by rartangem** [takevox/suikachau#9]
（再現できなかったので起きたことをそのまま）
挟まれる形で合成されたときに合成処理が終了せず、無限に合成SEが流れ、別のブロック同士を合成しようとしても合成されない

スクリーンショット
https://cdn.puraru-network.com/media/yukitochau_game_suika_err_001_20231006.png

**Comment by takevox** [comment]
報告ありがとうございます。
こちらでも再現してみようとしましたが再現できず。
0,7.0で回転バグへの対応で物理演算の設定を調整したので再現待ちとさせていただきたいと思います。

**Comment by rartangem** [comment]
お返事、ありがとうございます　当方でも同じような状況を用意して再現しようとゴタゴタやってみたもののどうにも再現できずじまいでございます。
物理演算の設定調整で無事に解決されていることを願っております
